name: MySQL Scheduler

on:
  schedule:
    # Start at 08:20 IST = 02:50 UTC
    - cron: "50 2 * * *"
    # Stop at 21:30 IST = 16:00 UTC
    - cron: "00 16 * * *"

  workflow_dispatch:

jobs:
  control:
    runs-on: ubuntu-latest

    steps:
      - name: Login Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Start MySQL
        if: github.event.schedule == '50 2 * * *'
        run: |
          az mysql flexible-server start \
            --name techbloggin-mysql \
            --resource-group rg-techblog-prod

      - name: Stop MySQL
        if: github.event.schedule == '00 16 * * *'
        run: |
          az mysql flexible-server stop \
            --name techbloggin-mysql \
            --resource-group rg-techblog-prod
